name: Test whodunit
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      digest:
        type: string
        required: true
  
jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.name }}
          subject-digest: ${{ inputs.digest }}
    
