on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  attestations: write
  actions: read

env:
  APP_NAME: 'attestations-demo-app'
  APP_SBOM_NAME: 'attestations-demo-app-sbom.spdx.json'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.get_digest.outputs.digest }}
      name: ${{env.APP_NAME}}
    steps:
      - name: Check out repo
        id: checkout_repo
        uses: actions/checkout@v4

      - name: Set up Go
        id: setup_go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
  
      - name: Build app
        id: build_app
        run: go build -o ${{env.APP_NAME}} .

      - name: Attest build provenance
        id: attest_build_provenance
        uses: actions/attest-build-provenance@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          subject-path: './${{env.APP_NAME}}'
          show-summary: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}
          path: ./${{env.APP_NAME}}
  sbom:
    uses: ./.github/workflows/sbom.yml
    needs:
      - build
    with:
      artifact-name: ${{ needs.build.outputs.name }}
    
