on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  attestations: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build SBOM
        uses: anchore/sbom-action@v0
        with:
          path: '.'

      - name: Build executable
        env:
          CGO_ENABLED: '0'
          PACKAGE: 'github.com/${{ github.repository }}'
          VERSION: '${{ github.ref_name }}'
          COMMIT_HASH: '${{ github.sha }}'
        run: ./scripts/build.sh

      - name: Attest build provenance
        id: attest_build_provenance
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            app-*

      - name: Rename attestations file
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv ${{steps.attest_build_provenance.outputs.bundle-path}} attestations-${{ github.ref_name }}.jsonl
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            Download and verify the provenance using the following commands:

            ## Linux

            ```shell
            curl -sSLO https://github.com/gillisandrew/attestations-demo/releases/download/${{ github.ref_name }}/app-linux-amd64-${{ github.ref_name }}
            gh attestation verify -o ${{ github.repository_owner }} app-linux-amd64-${{ github.ref_name }}
            ```

            ## MacOS

            ```shell
            curl -sSLO https://github.com/gillisandrew/attestations-demo/releases/download/${{ github.ref_name }}/app-darwin-arm64-${{ github.ref_name }}
            gh attestation verify -o ${{ github.repository_owner }} app-darwin-arm64-${{ github.ref_name }}
            ```

          files: |
            app-*
            attestations-${{ github.ref_name }}.jsonl
            *.spdx
            *.spdx.json
            
