on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build executable
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: '0'
          PACKAGE: 'github.com/${{ github.repository }}'
          VERSION: '${{ github.ref_name }}'
          COMMIT_HASH: '${{ github.sha }}'
        run: ./scripts/build.sh
      - name: Attest build provenance
        id: attest_build_provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            attestations-demo
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            attestations-demo
            ${{steps.attest_build_provenance.outputs.bundle-path}}
            