on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build executable
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: '0'
          PACKAGE: 'github.com/${{ github.repository }}'
          VERSION: v${{github.ref_name}}
          COMMIT_HASH: '${{ github.sha }}'
        run: ./scripts/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: attestations-demo
          name: attestations-demo-${{ github.run_id }}-${{ github.sha }}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: attestations-demo
            